In [1]:
import numpy as np

In [2]:
np.__version__

'1.24.3'

In [20]:
a = np.array([1, 2, 3])

In [8]:
a

array([1, 2, 3, 4, 5])

In [9]:
print(a.shape)

(5,)


In [10]:
print(a.dtype)

int64


In [11]:
print(a.ndim)

1


In [12]:
print(a.size)

5


In [14]:
print(a.itemsize)

8


In [17]:
print(a[1], a[3])

2 4


In [18]:
a[0] = 99

In [19]:
a

array([99,  2,  3,  4,  5])

In [21]:
b = a * np.array([2, 0, 2])

In [22]:
b

array([2, 0, 6])

In [23]:
l = [1, 2, 3]
a = np.array([1, 2, 3])
print(l)
print(a)

[1, 2, 3]
[1 2 3]


In [24]:
l = l +[4]
l

[1, 2, 3, 4]

In [25]:
a = a + np.array([4])
a

array([5, 6, 7])

In [26]:
###

In [27]:
l1 = [1, 2, 3]
l2 = [4, 5, 6]

In [28]:
dot = 0

In [29]:
for i in range(len(l1)):
    dot += l1[i] * l2[i]
    

In [30]:
dot

32

In [31]:
a1 = np.array(l1)
a2 = np.array(l2)

In [32]:
dot_np = np.dot(a1, a2)

In [33]:
dot_np

32

In [34]:
dot = a1 @ a2
dot

32

In [36]:
a = np.array([[1,2], [3, 4]])

In [37]:
np.shape(a)

(2, 2)

In [42]:
a[0][0]

1

In [43]:
a[:,1]

array([2, 4])

In [44]:
np.linalg.inv(a)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [45]:
np.linalg.det(a)

-2.0000000000000004

In [46]:
a = np.array([[1,2], [3,4], [5,6]])

In [47]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [48]:
bool_idx = a > 2

In [49]:
bool_idx

array([[False, False],
       [ True,  True],
       [ True,  True]])

In [50]:
a[bool_idx]

array([3, 4, 5, 6])

In [52]:
a = np.array([10, 20, 30, 40, 99, 6])
b = np.array([1,3,5])
a[b]

array([20, 40,  6])

In [61]:
even = np.argwhere(a%2==0).flatten()

In [62]:
a[even]

array([10, 20, 30, 40,  6])

In [63]:
a = np.arange(1,9)

In [64]:
a

array([1, 2, 3, 4, 5, 6, 7, 8])

In [65]:
a.shape

(8,)

In [71]:
b = a.reshape((4,2))

In [72]:
b

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [73]:
b = a[np.newaxis, :]

In [74]:
b

array([[1, 2, 3, 4, 5, 6, 7, 8]])

In [75]:
b.shape

(1, 8)

In [99]:
a = np.array([[1, 2], [3, 4]])

In [77]:
a

array([[1, 2],
       [3, 4]])

In [78]:
b = np.array([[5, 6]])

In [82]:
c = np.concatenate((a,b.T), axis=1)

In [83]:
c

array([[1, 2, 5],
       [3, 4, 6]])

In [84]:
a = np.array([1, 2, 3, 4])

In [85]:
b = np.array([5, 6, 7, 8])

In [86]:
c = np.hstack((a,b))

In [87]:
c

array([1, 2, 3, 4, 5, 6, 7, 8])

In [88]:
d = np.vstack((a,b))

In [89]:
d

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [101]:
a = np.array([[1,2,3], [4,5,6], [1,2,3], [4,5,6]])

In [92]:
b = np.array([1,0,1])

In [95]:
y = b + a

In [96]:
y

array([[2, 2, 4],
       [5, 5, 7],
       [2, 2, 4],
       [5, 5, 7]])

In [108]:
result = a.std()

In [109]:
result

1.707825127659933

In [110]:
x = np.array([1,2])

In [113]:
x.dtype

dtype('int64')

In [114]:
###

In [115]:
a = np.array([1,2,3])

In [116]:
b = a.copy()

In [117]:
b[0] = 99

In [119]:
print(a)
print(b)

[1 2 3]
[99  2  3]


In [121]:
a = np.zeros((2,3))

In [122]:
a

array([[0., 0., 0.],
       [0., 0., 0.]])

In [123]:
b = np.ones((4,5))

In [124]:
b

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [125]:
c = np.full((2,3), 8.8)

In [126]:
c

array([[8.8, 8.8, 8.8],
       [8.8, 8.8, 8.8]])

In [127]:
d = np.eye(6)

In [128]:
d

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [129]:
e = np.linspace(0,99,3)

In [130]:
e

array([ 0. , 49.5, 99. ])

In [131]:
a = np.random.random((3,2))

In [132]:
a

array([[0.21676508, 0.86777973],
       [0.08940412, 0.71508461],
       [0.42096096, 0.56676094]])

In [133]:
a = np.random.randn(3,2)

In [134]:
a

array([[-1.5836495 , -1.31813834],
       [ 0.53042085,  0.99967979],
       [ 1.87200193,  0.61740977]])

In [137]:
a = np.random.randint(1,9, size=(4,4))

In [138]:
a

array([[8, 7, 3, 2],
       [3, 7, 7, 1],
       [8, 5, 7, 7],
       [6, 3, 6, 8]])

In [139]:
###

In [140]:
a = np.array([[1,2], [3,4]])

In [141]:
eigenvalues, eigenvectors = np.linalg.eig(a)

In [146]:
#e_vec * e_val = A * e_vec
b =  eigenvectors[:,0] * eigenvalues[0] 

In [147]:
b

array([ 0.30697009, -0.21062466])

In [148]:
c = a @ eigenvectors[:,0]

In [149]:
print(np.allclose(b,c))

True


In [150]:
###

In [152]:
A = np.array([[1,1], [1.5,4.0]])
b = np.array([2200,5050])
x = np.linalg.inv(A).dot(b)

In [153]:
x

array([1500.,  700.])

In [155]:
y = np.linalg.solve(A,b)

In [156]:
y

array([1500.,  700.])